# base image
FROM nimlang/nim:1.0.4-regular

# install dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends libpq-dev netcat-openbsd

# set working directory
WORKDIR /usr/src/app

# install dependencies
COPY ./urlShortener.nimble .
RUN nimble refresh && nimble install jester

# copy app
COPY . .

# Nim environment
ENV NIM_ENV=production

# RUN script
CMD nimble c -ry -d:release src/urlShortener
