# base image
FROM nimlang/nim:1.0.4-regular

# install dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends libpq-dev netcat-openbsd

# set working directory
WORKDIR /usr/src/app

# install dependencies
COPY ./urlShortener.nimble .
RUN nimble refresh && nimble install jester

# copy app
COPY . .
RUN chmod +x entrypoint.sh

# Nim environment
ENV NIM_ENV=production

# RUN script
CMD ["-d:release"]
